title: "Talha Yorulmaz"
description: "Talha Yorulmaz Resmi Web Sitesi."
url: "https://talhayorulmaz.com"
email: talhayrlmz@gmail.com

author: "Talha Yorulmaz"


theme: minima 
plugins:
  - jekyll-seo-tag


markdown: kramdown
